AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
